# Generated by Django 2.1.7 on 2019-05-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='id_split',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
