# Generated by Django 2.1.7 on 2019-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiTiempo', '0002_municipio_id_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='colorfondo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='colorletras',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tamanoletras',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
